fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "hello@aquanote.com"
        sender_name: "AquaNote Postman"
    service:
        mailer: fos_user.mailer.twig_swift
